"use client"
import './globals.css'
import { Inter } from 'next/font/google'
import { createContext, useEffect, useState } from 'react'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import { loggedIn } from '@/services/auth'
import LoginForm from '@/components/LoginForm'
import { user as authUser } from '@/services/auth'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export const UserContext = createContext(authUser);

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const [user, setUser] = useState(authUser);
  const [logged, setLogged] = useState<boolean>(false);
  
  useEffect(() => {
    setLogged(loggedIn())
    setUser(authUser)
    console.log("Mounted!")
  }, [authUser])

  function refresh() {
    setLogged(loggedIn())
    setUser(authUser)
  }

  return (
    <html lang="fr">
      <body className={inter.className}>
      <>
      {logged ? (
        <>
        <UserContext.Provider value={user}>
          <Navbar refresh={refresh} />
        </UserContext.Provider>
        <UserContext.Provider value={user}>
        <main className='flex min-h-screen flex-col items-center p-24'>
          {children}
        </main>
        </UserContext.Provider>
          <Footer />
        </>
        ) :
        <main className='flex min-h-screen flex-col items-center p-24'>
          <LoginForm refresh={refresh} />
        </main>
      }
      </>
      </body>
    </html>
  )
}
